language: cpp

cache:
  apt: true

matrix:
  include:
    - env: CC=gcc-8 CXX=g++-8
      os: linux
      sudo: require
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8

    - env: CC=clang-7 CXX=clang++-7
      sudo: false
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
          packages:
            - clang-7

    - os: osx
      osx_image: xcode10.1

    - os: windows

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build . --config debug
  - ctest -V -C debug
