language: cpp

cache:
  apt: true

matrix:
  include:
    - env: CC=gcc-7 CXX=g++-7
      os: linux
      dist: trusty
      sudo: require
      addons:
        apt:
          sources: *sources
          packages:
            - gcc-7
            - g++-7

    - env: CC=clang-5.0 CXX=clang++-5.0
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0

    - os: osx
      osx_image: xcode9.3

      
    - os: windows

script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build . --config debug
    - ctest -V -C debug