language: cpp

cache:
  apt: true

matrix:
  include:
    - env: CC=gcc-8 CXX=g++-8
      os: linux
      sudo: require
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8

    - compiler: clang
      env:
        - CC=clang
        - CXX=clang++

    - compiler: clang
      os: osx
      env:
        - CC=clang
        - CXX=clang
        
    - os: windows

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build . --config debug
  - ctest -V -C debug
