language: cpp

cache:
  apt: true

matrix:
  include:
    - env: CC=gcc-8.2 CXX=g++-8.2
      os: linux
      sudo: require
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8.2
            - g++-8.2

    - env: CC=clang-7.0 CXX=clang++-7.0
      sudo: require
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7.0
          packages:
            - clang-7.0

    - os: osx
      osx_image: xcode10.1

    - os: windows

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build . --config debug
  - ctest -V -C debug
